version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-container
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./api/.env
    networks:
      - app-network

  web:
    build:
      context: ./web
      target: production
      dockerfile: Dockerfile
    container_name: web-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./web/.env      
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
