version: '3.8'

services:
  notifications-system:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: npm run start:prod
